# ============================================
# docker-compose.yml
# ============================================

version: '3.8'

services:
  web:
    build: .
    container_name: news-management-system
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/newsdb
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./news.db:/app/news.db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - news-network

  db:
    image: postgres:15-alpine
    container_name: news-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - news-network

  redis:
    image: redis:7-alpine
    container_name: news-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - news-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: news-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - news-network

volumes:
  postgres_data:
  redis_data:

networks:
  news-network:
    driver: bridge
